ALTER TABLE users ADD COLUMN height REAL DEFAULT 175.0;
ALTER TABLE users ADD COLUMN weight REAL DEFAULT 75.0;
ALTER TABLE users ADD COLUMN goal TEXT DEFAULT 'Strength';
ALTER TABLE users ADD COLUMN experience TEXT DEFAULT 'Beginner';
